### ISSUE TITLE
hello guys, how can this implementation with custom adapter?

### ISSUE THREAD

**Issue by candratop3** [Jumman04/Jummania-Slider#18]
hello guys, how can this implementation with custom adapter?
thanks for reply

**Comment by Jumman04** [comment]
Hi, we have tested jslider in RecyclerView.Adapter, we got very bad performance with lagging while scrolling.
But after some time after stopping scrolling I saw jslider running nicely...

However, **We would never recommend to implement JSlider in RecycleView or ListView...**

https://github.com/Jumman04/Jummania-Slider/assets/113237846/e04d0626-d8bd-4a22-9a1c-46e47f5fbf22

**Comment by Jumman04** [comment]
@candratop3  Hi,
We have tested jslider in RecyclerView.Adapter.
We was goted many issues and the latest update, we fixed them.
Remember, if you want to implement jslider in recycleview or listview then you must specify height of jslider.
