### ISSUE TITLE
Java-specific "Expression expected" bug with setSlideAnimation

### ISSUE THREAD

**Issue by Jumman04** [Jumman04/Jummania-Slider#9]
### Bug Description
When attempting to use `jSlider.setSlideAnimation(AnimationTypes.ANTI_CLOCK_SPIN);` in Java, an "Expression expected" error is encountered. This issue does not manifest in Kotlin.

### Additional Information
The issue appears to be Java-specific and is related to the private access of `ANTI_CLOCK_SPIN` in the `AnimationTypes` sealed class. The fix should address this accessibility problem, ensuring compatibility with both Kotlin and Java.

### Expected Behavior
The code should compile without errors in both Kotlin and Java.

**Comment by sarowarhosen03** [comment]
It's good that  Jummania-Slider 3.5 support java. Nowdays most of the android dev shift to kotlin.  I think drop support of Java isn't a bad deal. Go ahead with kotlin

**Comment by Jumman04** [comment]
I appreciate your feedback, @sarowarhosen03 .

It's true that Kotlin has gained significant traction among Android developers, Kotlin is a more modern and concise language that is better suited for Android development. **It is also the language that Google is now recommending for Android development.**

**Comment by sarowarhosen03** [comment]
> I appreciate your feedback, @sarowarhosen03 .
> 
> It's true that Kotlin has gained significant traction among Android developers, Kotlin is a more modern and concise language that is better suited for Android development. **It is also the language that Google is now recommending for Android development.**

Yaap . You're right

**Comment by Jumman04** [comment]
**Update:** The bug has been fixed.
